// All four read-only, syntax-highlighted compiler output ide live here.
// Each one is generated by `code_view!` -- add a new output stage by adding
// one more invocation at the bottom of this file.

use crate::view::common::{centered_placeholder, scrollable_code};
use crate::view::{CompilationState, CompilerView, ProgramCatalog};
use crate::view::{highlight_assembly, highlight_ast, highlight_ir};

/// Generates a read-only, scrollable, syntax-highlighted view of one
/// `CompilationState` field.
///
/// Parameters
/// - `$name`      -- struct name (e.g. `IrView`)
/// - `$title`     -- tab label (e.g. `"IR"`)
/// - `$field`     -- `CompilationState` field (e.g. `ir`)
/// - `$highlight` -- highlighter fn: `fn(&Style, &str) -> LayoutJob`
/// - `$empty`     -- placeholder shown when the field is empty
macro_rules! code_view {
    ($name:ident, $title:literal, $field:ident, $highlight:expr, $empty:literal) => {
        #[derive(Default, Clone)]
        pub struct $name;

        impl CompilerView for $name {
            fn title(&self) -> &'static str {
                $title
            }

            fn ui(
                &mut self,
                ui: &mut egui::Ui,
                _ctx: &egui::Context,
                state: &mut CompilationState,
                _catalog: &mut ProgramCatalog,
            ) {
                if state.$field.is_empty() {
                    centered_placeholder(ui, $empty);
                    return;
                }
                let mut job = $highlight(ui.style(), &state.$field);
                job.wrap.max_width = f32::INFINITY;
                // Use the panel's own id as the salt so duplicate ide each
                // get independent scroll state.
                scrollable_code(ui, ui.id(), job);
            }

            fn clone_box(&self) -> Box<dyn CompilerView> {
                Box::new(self.clone())
            }
        }
    };
}

code_view!(
    TokensView,
    "Tokens",
    tokens,
    highlight_ast,
    "Compile source to generate tokens."
);
code_view!(
    AstView,
    "AST",
    ast,
    highlight_ast,
    "Compile source to generate AST."
);
code_view!(
    IrView,
    "IR",
    ir,
    highlight_ir,
    "Compile source to generate IR."
);
code_view!(
    AssemblyView,
    "Assembly",
    asm,
    highlight_assembly,
    "Compile source to generate assembly."
);
