use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests/unit");
    println!("cargo:rerun-if-changed=tests/integration");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("generated_tests.rs");

    let mut files = Vec::new();
    collect_rs_files(&manifest_dir.join("tests/unit"), &mut files);
    collect_rs_files(&manifest_dir.join("tests/integration"), &mut files);
    files.sort();

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit.\n");
    output.push_str("// This file includes every test module under tests/unit and tests/integration.\n\n");

    for path in files {
        let rel = path.strip_prefix(&manifest_dir).expect("path under manifest dir");
        let module_name = module_name_for(rel);
        let absolute = path.display().to_string();
        output.push_str(&format!(
            "#[path = r#\"{absolute}\"#]\nmod {module_name};\n"
        ));
    }

    fs::write(&generated, output).expect("failed to write generated test harness");
}

fn collect_rs_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_rs_files(&path, files);
            } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
                files.push(path);
            }
        }
    }
}

fn module_name_for(path: &Path) -> String {
    path.with_extension("")
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("_")
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}


