use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests/integration");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("generated_tests.rs");

    let mut files = Vec::new();
    collect_rs_files(&manifest_dir.join("tests/integration"), &mut files);
    files.sort();

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit.\n");
    output.push_str("// This file includes every test module under tests/integration.\n\n");

    for path in files {
        let rel = path
            .strip_prefix(&manifest_dir)
            .expect("path under manifest dir");
        let module_name = module_name_for(rel);
        let absolute = path.display().to_string();
        output.push_str(&format!(
            "#[path = r#\"{absolute}\"#]\nmod {module_name};\n"
        ));
    }

    fs::write(&generated, output).expect("failed to write generated test harness");

    generate_userspace(&manifest_dir, &out_dir);
}

fn collect_rs_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_rs_files(&path, files);
            } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
                files.push(path);
            }
        }
    }
}

fn module_name_for(path: &Path) -> String {
    path.with_extension("")
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("_")
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn generate_userspace(manifest_dir: &Path, out_dir: &Path) {
    let user_dir = manifest_dir.join("programs/user");
    println!("cargo:rerun-if-changed={}", user_dir.display());

    let mut build_files = Vec::new();
    collect_build_files(&user_dir, &mut build_files);
    build_files.sort();

    let mut programs: Vec<Program> = build_files.iter().map(|path| Program::load(path)).collect();
    programs.sort_by(|a, b| (a.kind.rank(), &a.name).cmp(&(b.kind.rank(), &b.name)));

    let code = render_userspace(&programs);
    fs::write(out_dir.join("userspace.rs"), code).expect("failed to write userspace.rs");
}

fn collect_build_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_build_files(&path, out);
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("build") {
            out.push(path);
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    Tool,
    Demo,
    Example,
    Fixture,
}

impl Kind {
    fn parse(value: &str) -> Self {
        match value {
            "tool" => Self::Tool,
            "demo" => Self::Demo,
            "example" => Self::Example,
            "fixture" => Self::Fixture,
            other => panic!("unknown program kind `{other}`"),
        }
    }

    fn variant(self) -> &'static str {
        match self {
            Self::Tool => "Tool",
            Self::Demo => "Demo",
            Self::Example => "Example",
            Self::Fixture => "Fixture",
        }
    }

    fn rank(self) -> u8 {
        self as u8
    }
}

struct Program {
    name: String,
    title: String,
    description: String,
    kind: Kind,
    install_path: Option<String>,
    source: String,
    build_path: String,
    import_closure: bool,
    mangle_symbols: bool,
    layout_const: Option<String>,
    layout_path: Option<String>,
}

impl Program {
    fn load(build_path: &Path) -> Self {
        println!("cargo:rerun-if-changed={}", build_path.display());
        let text = fs::read_to_string(build_path).expect("read .build");
        let manifest = build_manifest::parse(&text)
            .unwrap_or_else(|err| panic!("{}: {err}", build_path.display()));
        let dir = build_path.parent().expect("manifest parent");
        let field = |key: &str| {
            manifest
                .string(key)
                .unwrap_or_else(|| panic!("{}: missing `{key}`", build_path.display()))
        };

        let name = field("name");
        let kind = Kind::parse(&field("kind"));
        let source = abs(dir, &field("root"));
        println!("cargo:rerun-if-changed={source}");
        let import_closure = manifest
            .bool("import_closure")
            .expect("import_closure")
            .unwrap_or(true);
        let mangle_symbols = manifest
            .bool("mangle_symbols")
            .expect("mangle_symbols")
            .unwrap_or(true);

        let (layout_const, layout_path) = match manifest.get("source_prelude") {
            Some(rel) => {
                let path = abs(dir, rel);
                println!("cargo:rerun-if-changed={path}");
                (Some(format!("{}_LAYOUT", name.to_uppercase())), Some(path))
            }
            None => (None, None),
        };

        Self {
            name,
            title: field("title"),
            description: field("description"),
            kind,
            install_path: manifest.string("install_path"),
            source,
            build_path: build_path.display().to_string(),
            import_closure,
            mangle_symbols,
            layout_const,
            layout_path,
        }
    }
}

fn render_userspace(programs: &[Program]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from programs/user/**/*.build - do not edit.\n");

    for program in programs {
        let source_const = source_const_name(&program.name);
        writeln!(
            out,
            "pub const {source_const}: &str = include_str!(\"{}\");",
            program.source
        )
        .expect("write");
        if let (Some(name), Some(path)) = (&program.layout_const, &program.layout_path) {
            writeln!(out, "pub const {name}: &str = include_str!(\"{path}\");").expect("write");
        }
    }

    out.push_str("\npub static PROGRAMS: &[UserProgram] = &[\n");
    for program in programs {
        let install = match &program.install_path {
            Some(path) => format!("Some(\"{}\")", escape(path)),
            None => "None".to_owned(),
        };
        let layout = program.layout_const.as_deref().unwrap_or("\"\"");
        writeln!(
            out,
            "    UserProgram {{ name: \"{name}\", title: \"{title}\", description: \"{desc}\", \
             kind: UserProgramKind::{kind}, install_path: {install}, source: {source}, \
             source_path: \"{source_path}\", build_path: \"{build_path}\", \
             import_closure: {import_closure}, \
             mangle_symbols: {mangle_symbols}, layout: {layout} }},",
            name = escape(&program.name),
            title = escape(&program.title),
            desc = escape(&program.description),
            kind = program.kind.variant(),
            source = source_const_name(&program.name),
            source_path = escape(&program.source),
            build_path = escape(&program.build_path),
            import_closure = program.import_closure,
            mangle_symbols = program.mangle_symbols,
        )
        .expect("write");
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Look up a program by its stable `name` key.\n\
         pub fn program(name: &str) -> Option<&'static UserProgram> {\n\
             PROGRAMS.iter().find(|p| p.name == name)\n\
         }\n\n\
         /// Look up a generated program source by flat registry name.\n\
         pub fn module_source(name: &str) -> Option<&'static str> {\n\
             program(name).map(|program| program.source)\n\
         }\n",
    );
    out
}

fn source_const_name(name: &str) -> String {
    match name {
        "hello" => "USER_HELLO".to_owned(),
        "ex_array" => "EXAMPLE_ARRAY_S".to_owned(),
        "ex_hello_hll" => "CC_DEMO_HLL".to_owned(),
        "ex_stdlib" => "EXAMPLE_STDLIB_S".to_owned(),
        "fx_hello_hll" => "CC_HELLO_HLL".to_owned(),
        "fx_hello_s" => "CC_HELLO_S".to_owned(),
        other => other
            .chars()
            .map(|ch| {
                if ch.is_ascii_alphanumeric() {
                    ch.to_ascii_uppercase()
                } else {
                    '_'
                }
            })
            .collect(),
    }
}

fn abs(dir: &Path, rel: &str) -> String {
    dir.join(rel).to_string_lossy().replace('\\', "/")
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
