pub(crate) mod assembly_emitter;
pub mod compiler_rv64;
pub(crate) mod data_section;
pub(crate) mod frame_context;
pub(crate) mod function_context;
pub(crate) mod peephole;
pub(crate) mod register_allocator;
pub(crate) mod slot_coloring;
pub(crate) mod type_utils;
