use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");
    for dir in ["boot", "kernel", "stdlib"] {
        println!("cargo:rerun-if-changed={dir}");
        watch_dir(Path::new(dir));
    }

    let mut sources = Vec::new();
    collect_sources(&manifest_dir.join("kernel"), &manifest_dir, &mut sources);
    collect_sources(&manifest_dir.join("stdlib"), &manifest_dir, &mut sources);
    sources.sort_by(|a, b| a.key.cmp(&b.key));

    let code = render_sources(&sources);
    fs::write(out_dir.join("sources.rs"), code).expect("write sources.rs");
}

fn watch_dir(dir: &Path) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            watch_dir(&path);
        } else {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn collect_sources(dir: &Path, manifest_dir: &Path, out: &mut Vec<Source>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_sources(&path, manifest_dir, out);
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("hll") {
            continue;
        }
        let rel = path.strip_prefix(manifest_dir).expect("source under crate");
        let key = source_key(rel);
        out.push(Source { key, path });
    }
}

fn source_key(rel: &Path) -> String {
    let components: Vec<String> = rel
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect();
    let stem = rel
        .file_stem()
        .and_then(|stem| stem.to_str())
        .expect("hll stem");

    if components == ["stdlib", "hosted", "console.hll"] {
        "console_hosted".to_owned()
    } else if components == ["stdlib", "hosted", "cstr.hll"] {
        "cstr_hosted".to_owned()
    } else if components == ["stdlib", "hosted", "memory_allocator.hll"] {
        "memory_allocator_hosted".to_owned()
    } else if components == ["stdlib", "hosted", "runtime.hll"] {
        "runtime_hosted".to_owned()
    } else if components == ["stdlib", "hosted", "sys.hll"] {
        "sys_hosted".to_owned()
    } else if components == ["kernel", "core", "entry.hll"] {
        "kernel_entry".to_owned()
    } else {
        stem.to_owned()
    }
}

fn render_sources(sources: &[Source]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from kernel/ and stdlib/ - do not edit.\n");
    out.push_str("pub static SOURCES: &[(&str, &str)] = &[\n");
    for source in sources {
        writeln!(
            out,
            "    (\"{}\", include_str!(\"{}\")),",
            escape(&source.key),
            source.path.to_string_lossy().replace('\\', "/")
        )
        .expect("write");
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// Look up a bundled kernel or stdlib module by its stable registry key.\n\
         pub fn module_source(name: &str) -> Option<&'static str> {\n\
             SOURCES.iter().find(|(key, _)| *key == name).map(|(_, source)| *source)\n\
         }\n",
    );
    out
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

struct Source {
    key: String,
    path: PathBuf,
}
